import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import ws from 'ws';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.resolve(__dirname, '../.env.local') });

const SUPABASE_URL = process.env.VITE_SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error('Missing Supabase credentials');
}

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: { persistSession: false },
  realtime: { transport: ws }
});

const CITY_ID = '97df4146-ef55-4634-855f-cbb226603a4c';

const AC_MAPPINGS: Record<string, string> = {
  'B.T.M Layout': 'B.T.M. Layout',
  'Chamrajapet': 'Chamrajpet',
  'Gandhinagara': 'Gandhi Nagar',
  'Padmanabanagar': 'Padmanabhanagar',
  'Rajajinagar': 'Rajaji Nagar',
  'Vijayanagar': 'Vijay Nagar'
};

function slugify(text: string) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, '');
}

async function run() {
  console.log('Reading geojson...');
  const geojsonPath = path.resolve(__dirname, '../public/data/bengaluru-wards.geojson');
  const rawData = fs.readFileSync(geojsonPath, 'utf8');
  const geojson = JSON.parse(rawData);

  console.log(`Found ${geojson.features.length} features.`);

  console.log('Fetching assembly constituencies...');
  const { data: acData, error: acError } = await supabase
    .from('assembly_constituencies')
    .select('id, name');

  if (acError) {
    throw new Error(`Failed to fetch ACs: ${acError.message}`);
  }

  const acNameToId: Record<string, string> = {};
  for (const ac of acData) {
    acNameToId[ac.name.toLowerCase()] = ac.id;
  }

  const wardsToInsert = [];

  for (const feature of geojson.features) {
    const props = feature.properties;

    let wardName = props.ward_name;
    if (wardName.includes(' - ')) {
      wardName = wardName.split(' - ')[1].trim();
    }

    const wardNumber = parseInt(props.ward_id, 10);
    const corporation = props.Corporation;

    let acName = props.ac;
    if (AC_MAPPINGS[acName]) {
      acName = AC_MAPPINGS[acName];
    }

    const acId = acNameToId[acName.toLowerCase()];
    if (!acId) {
      console.warn(`WARNING: Could not find AC ID for ${acName} in DB!`);
      continue;
    }

    const population = props.TOT_P || 0;
    const slug = `${slugify(wardName)}-w${wardNumber}`;

    wardsToInsert.push({
      city_id: CITY_ID,
      ac_id: acId,
      ward_number: wardNumber,
      name: wardName,
      slug,
      corporation,
      population
    });
  }

  console.log(`Prepared ${wardsToInsert.length} wards to insert.`);

  // Write a migration file to bypass RLS via CI/CD
  let sql = `-- Seed all 369 wards generated by script\n\n`;
  sql += `DO $$\nBEGIN\n`;
  for (const w of wardsToInsert) {
    sql += `  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('${w.city_id}', '${w.ac_id}', ${w.ward_number}, '${w.name.replace(/'/g, "''")}', '${w.slug}', '${w.corporation}', ${w.population})
  ON CONFLICT (slug) DO NOTHING;\n`;
  }
  sql += `END $$;\n`;
  
  const migPath = path.resolve(__dirname, '../supabase/migrations/007_seed_369_wards.sql');
  fs.writeFileSync(migPath, sql);
  console.log('Generated migration file:', migPath);

  // Try to insert directly as requested (will fail if RLS is enforced)
  console.log('Attempting direct insert...');
  const CHUNK_SIZE = 100;
  for (let i = 0; i < wardsToInsert.length; i += CHUNK_SIZE) {
    const chunk = wardsToInsert.slice(i, i + CHUNK_SIZE);
    const { error } = await supabase.from('wards').insert(chunk);
    if (error) {
      console.warn(`Direct insert failed for chunk ${i} to ${i + CHUNK_SIZE}:`, error.message);
    } else {
      console.log(`Inserted chunk ${i} to ${i + chunk.length} directly.`);
    }
  }

  console.log('Done!');
}

run().catch(console.error);
