-- Seed all 369 wards generated by script

DO $$
BEGIN
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2d2fa9da-a739-4afd-8693-8db51e3aab99', 25, 'Vinayaka Layout', 'vinayaka-layout-w25', 'West', 20170)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '87e7fdba-f2b4-4b68-99f2-c373b8032059', 2, 'Aerocity', 'aerocity-w2', 'North', 20655)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '87e7fdba-f2b4-4b68-99f2-c373b8032059', 3, 'Chowdeshwari ward', 'chowdeshwari-ward-w3', 'North', 26795)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 15, 'Ramamurthy Nagara', 'ramamurthy-nagara-w15', 'East', 17257)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a22834e4-c130-4429-8557-16627aa8596b', 58, 'Nagashettyhalli', 'nagashettyhalli-w58', 'North', 23289)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '3410ebdb-6c32-48a2-a567-9a10b793984b', 21, 'Kogilu', 'kogilu-w21', 'North', 28728)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 46, 'Yamalur', 'yamalur-w46', 'East', 17526)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '041c179b-1295-46cd-9220-2dc5f68d372d', 24, 'Agaram', 'agaram-w24', 'Central', 28081)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f440de02-f85a-4eef-a795-0f242b99bcf0', 72, 'Dasarahalli', 'dasarahalli-w72', 'North', 29082)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '04551a39-b049-4bd8-b481-588498172c2e', 11, 'Old Baiyappanahalli', 'old-baiyappanahalli-w11', 'Central', 18858)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 16, 'Kotthur', 'kotthur-w16', 'East', 14653)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f440de02-f85a-4eef-a795-0f242b99bcf0', 69, 'Bagalagunte', 'bagalagunte-w69', 'North', 28685)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '25ab31b1-80b2-49e8-81e4-22bd802dfd9e', 34, 'Subbayanapalya', 'subbayanapalya-w34', 'North', 22175)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f440de02-f85a-4eef-a795-0f242b99bcf0', 68, 'Mallasandra', 'mallasandra-w68', 'North', 26890)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f440de02-f85a-4eef-a795-0f242b99bcf0', 70, 'Manjunatha Nagar', 'manjunatha-nagar-w70', 'North', 27870)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'b3b4fba5-22d7-4d03-bf47-6908b4a4205a', 2, 'Kadirenahalli', 'kadirenahalli-w2', 'South', 19937)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2d2fa9da-a739-4afd-8693-8db51e3aab99', 60, 'Jalahalli', 'jalahalli-w60', 'North', 23400)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 14, 'K.R Pura', 'k-r-pura-w14', 'East', 14930)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '481035e9-c93a-4424-985a-293e5755ebdf', 20, 'Kengeri Kote ward', 'kengeri-kote-ward-w20', 'West', 19339)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f92a4030-38b1-4765-baab-a168a3c56049', 39, 'Gottigere', 'gottigere-w39', 'South', 21839)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f92a4030-38b1-4765-baab-a168a3c56049', 36, 'Beguru', 'beguru-w36', 'South', 18605)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '93d13307-f71b-4912-b4bc-6a13f3611c33', 41, 'V.V Puram', 'v-v-puram-w41', 'Central', 19813)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '25ab31b1-80b2-49e8-81e4-22bd802dfd9e', 35, 'Kammanahalli', 'kammanahalli-w35', 'North', 26646)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '9ef1e023-b17a-4f6f-8a7e-e325a20d7bcb', 7, 'Byrasandra', 'byrasandra-w7', 'South', 21108)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '9ef1e023-b17a-4f6f-8a7e-e325a20d7bcb', 8, 'Tilak Nagara', 'tilak-nagara-w8', 'South', 25625)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2d2fa9da-a739-4afd-8693-8db51e3aab99', 63, 'J.P PARK', 'j-p-park-w63', 'North', 22172)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'eca9e102-8d9b-4385-8a19-f09fb5756114', 51, 'Old Guddadahalli', 'old-guddadahalli-w51', 'Central', 25228)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 4, 'Babusab Palya', 'babusab-palya-w4', 'East', 19361)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'b3b4fba5-22d7-4d03-bf47-6908b4a4205a', 4, 'Banashankari Temple Ward', 'banashankari-temple-ward-w4', 'South', 22549)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f440de02-f85a-4eef-a795-0f242b99bcf0', 71, 'Nele Maheshwaramma Temple Ward', 'nele-maheshwaramma-temple-ward-w71', 'North', 27033)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 45, 'Marathahalli', 'marathahalli-w45', 'East', 17823)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f92a4030-38b1-4765-baab-a168a3c56049', 45, 'Konanakunte', 'konanakunte-w45', 'South', 20525)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '9ef1e023-b17a-4f6f-8a7e-e325a20d7bcb', 13, 'Marenahalli South', 'marenahalli-south-w13', 'South', 23458)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f92a4030-38b1-4765-baab-a168a3c56049', 44, 'Harinagar', 'harinagar-w44', 'South', 21893)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 2, 'Horamavu', 'horamavu-w2', 'East', 14756)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a22834e4-c130-4429-8557-16627aa8596b', 50, 'Dinnur', 'dinnur-w50', 'North', 27395)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 25, 'L.B Shastri Nagar', 'l-b-shastri-nagar-w25', 'East', 14946)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f440de02-f85a-4eef-a795-0f242b99bcf0', 66, 'Kammagondanahalli', 'kammagondanahalli-w66', 'North', 20542)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '9ef1e023-b17a-4f6f-8a7e-e325a20d7bcb', 10, 'Abdul Kalam Nagar', 'abdul-kalam-nagar-w10', 'South', 23124)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '09e1ec39-9f66-46d8-969c-a99f11b7029d', 45, 'Kushal Nagar', 'kushal-nagar-w45', 'North', 19954)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 11, 'Krishnanagar', 'krishnanagar-w11', 'East', 16000)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f92a4030-38b1-4765-baab-a168a3c56049', 43, 'Bheereshwara Nagar', 'bheereshwara-nagar-w43', 'South', 26950)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'b3b4fba5-22d7-4d03-bf47-6908b4a4205a', 3, 'Yarab nagar', 'yarab-nagar-w3', 'South', 20832)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f92a4030-38b1-4765-baab-a168a3c56049', 42, 'RBI Layout', 'rbi-layout-w42', 'South', 22569)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 1, 'K Narayanapura', 'k-narayanapura-w1', 'East', 15003)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 39, 'Hagaduru', 'hagaduru-w39', 'East', 15105)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '04551a39-b049-4bd8-b481-588498172c2e', 13, 'Krishnaiahnapalya', 'krishnaiahnapalya-w13', 'Central', 19302)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'b3b4fba5-22d7-4d03-bf47-6908b4a4205a', 1, 'Padmanabhanagara', 'padmanabhanagara-w1', 'South', 23419)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f92a4030-38b1-4765-baab-a168a3c56049', 48, 'Vasanthapura', 'vasanthapura-w48', 'South', 22830)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'b3b4fba5-22d7-4d03-bf47-6908b4a4205a', 6, 'Gowdanapalya', 'gowdanapalya-w6', 'South', 24691)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '60a0221e-9762-4376-b9f6-6b99459671ca', 63, 'Okalipuram', 'okalipuram-w63', 'Central', 27815)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'b3b4fba5-22d7-4d03-bf47-6908b4a4205a', 5, 'Kane Muneshwara Ward', 'kane-muneshwara-ward-w5', 'South', 22022)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '04551a39-b049-4bd8-b481-588498172c2e', 9, 'Hoysala Nagara Central', 'hoysala-nagara-central-w9', 'Central', 27798)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '481035e9-c93a-4424-985a-293e5755ebdf', 52, 'Talagattapura', 'talagattapura-w52', 'South', 23797)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f92a4030-38b1-4765-baab-a168a3c56049', 50, 'Sarvabhouma Nagar', 'sarvabhouma-nagar-w50', 'South', 25256)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '25ab31b1-80b2-49e8-81e4-22bd802dfd9e', 25, 'Govindapura', 'govindapura-w25', 'North', 21432)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'eca9e102-8d9b-4385-8a19-f09fb5756114', 53, 'Rayapuram', 'rayapuram-w53', 'Central', 23438)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f92a4030-38b1-4765-baab-a168a3c56049', 40, 'Anjanapura', 'anjanapura-w40', 'South', 23865)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 59, 'Vijaya Bank Layout', 'vijaya-bank-layout-w59', 'South', 27787)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '09e1ec39-9f66-46d8-969c-a99f11b7029d', 41, 'Periyar Nagar', 'periyar-nagar-w41', 'North', 19963)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'eca9e102-8d9b-4385-8a19-f09fb5756114', 52, 'Padarayanapura', 'padarayanapura-w52', 'Central', 25833)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f92a4030-38b1-4765-baab-a168a3c56049', 46, 'Yelachenahalli', 'yelachenahalli-w46', 'South', 23953)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a22834e4-c130-4429-8557-16627aa8596b', 59, 'Geddalahalli', 'geddalahalli-w59', 'North', 23331)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f92a4030-38b1-4765-baab-a168a3c56049', 51, 'Subramanyapura', 'subramanyapura-w51', 'South', 27304)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2d2fa9da-a739-4afd-8693-8db51e3aab99', 35, 'Goraguntepalya', 'goraguntepalya-w35', 'West', 21462)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2d2fa9da-a739-4afd-8693-8db51e3aab99', 28, 'Kottegepalya', 'kottegepalya-w28', 'West', 22872)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2d2fa9da-a739-4afd-8693-8db51e3aab99', 62, 'Brundavana Nagara', 'brundavana-nagara-w62', 'North', 28749)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '87e7fdba-f2b4-4b68-99f2-c373b8032059', 5, 'Yelahanka Satellite Town', 'yelahanka-satellite-town-w5', 'North', 29889)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2d2fa9da-a739-4afd-8693-8db51e3aab99', 22, 'Bangarappa Nagara', 'bangarappa-nagara-w22', 'West', 28414)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f92a4030-38b1-4765-baab-a168a3c56049', 49, 'Uttarahalli', 'uttarahalli-w49', 'South', 25302)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2d2fa9da-a739-4afd-8693-8db51e3aab99', 64, 'Yeshwanthpura', 'yeshwanthpura-w64', 'North', 20236)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f92a4030-38b1-4765-baab-a168a3c56049', 37, 'Yelenahalli', 'yelenahalli-w37', 'South', 18609)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '04551a39-b049-4bd8-b481-588498172c2e', 17, 'Kaggadasapura', 'kaggadasapura-w17', 'Central', 20794)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f92a4030-38b1-4765-baab-a168a3c56049', 38, 'Doddakammanahalli', 'doddakammanahalli-w38', 'South', 19891)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 28, 'Byrathi', 'byrathi-w28', 'East', 13969)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f92a4030-38b1-4765-baab-a168a3c56049', 41, 'Kothanur', 'kothanur-w41', 'South', 23161)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 19, 'K.S. Nissar Ahmed Ward', 'k-s-nissar-ahmed-ward-w19', 'East', 15446)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a22834e4-c130-4429-8557-16627aa8596b', 57, 'Bhoopasandra', 'bhoopasandra-w57', 'North', 25193)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '9ef1e023-b17a-4f6f-8a7e-e325a20d7bcb', 15, 'Shakambarinagara', 'shakambarinagara-w15', 'South', 25845)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a22834e4-c130-4429-8557-16627aa8596b', 56, 'Hebbal', 'hebbal-w56', 'North', 27422)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a22834e4-c130-4429-8557-16627aa8596b', 52, 'Vishwanatha Nagenahalli', 'vishwanatha-nagenahalli-w52', 'North', 28859)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '45cfd0c6-6510-4bff-b87d-1a378b587029', 4, 'Sampangirama Nagar', 'sampangirama-nagar-w4', 'Central', 27874)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 10, 'Basavanapura', 'basavanapura-w10', 'East', 16224)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f92a4030-38b1-4765-baab-a168a3c56049', 35, 'Vishwapriya Nagara', 'vishwapriya-nagara-w35', 'South', 19281)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '45cfd0c6-6510-4bff-b87d-1a378b587029', 8, 'Halasuru', 'halasuru-w8', 'Central', 24019)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f92a4030-38b1-4765-baab-a168a3c56049', 33, 'Naganathapura', 'naganathapura-w33', 'South', 18599)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'fac027e0-792d-47b5-9d3a-699b0f9c95d1', 49, 'Aramane Nagara', 'aramane-nagara-w49', 'West', 26145)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '04551a39-b049-4bd8-b481-588498172c2e', 12, 'Kasturi Nagar', 'kasturi-nagar-w12', 'Central', 19331)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '32c35def-a2ce-4fab-8011-d7797617a42a', 79, 'Nagarbhavi', 'nagarbhavi-w79', 'West', 28194)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 41, 'Munnenkolalu', 'munnenkolalu-w41', 'East', 20977)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f92a4030-38b1-4765-baab-a168a3c56049', 34, 'Chikkathoguru', 'chikkathoguru-w34', 'South', 18868)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '87e7fdba-f2b4-4b68-99f2-c373b8032059', 6, 'Doddabettahalli', 'doddabettahalli-w6', 'North', 29553)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a22834e4-c130-4429-8557-16627aa8596b', 55, 'Ganganagar', 'ganganagar-w55', 'North', 25186)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 17, 'Vijinapura', 'vijinapura-w17', 'East', 15133)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'eca9e102-8d9b-4385-8a19-f09fb5756114', 49, 'Kasturbha Nagar', 'kasturbha-nagar-w49', 'Central', 24488)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '87e7fdba-f2b4-4b68-99f2-c373b8032059', 1, 'Raja Kempegowda ward', 'raja-kempegowda-ward-w1', 'North', 21561)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '9ef1e023-b17a-4f6f-8a7e-e325a20d7bcb', 11, 'Jayanagar East', 'jayanagar-east-w11', 'South', 22697)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '93d13307-f71b-4912-b4bc-6a13f3611c33', 33, 'Dharmaraya Swamy Temple Ward', 'dharmaraya-swamy-temple-ward-w33', 'Central', 18905)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '93d13307-f71b-4912-b4bc-6a13f3611c33', 38, 'Kanakanapalya', 'kanakanapalya-w38', 'Central', 20054)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '60a0221e-9762-4376-b9f6-6b99459671ca', 62, 'Swatantra Palya Ward', 'swatantra-palya-ward-w62', 'Central', 28137)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a22834e4-c130-4429-8557-16627aa8596b', 54, 'Gangenahalli', 'gangenahalli-w54', 'North', 24120)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '9ef1e023-b17a-4f6f-8a7e-e325a20d7bcb', 14, 'J.P Nagar', 'j-p-nagar-w14', 'South', 22264)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '9ef1e023-b17a-4f6f-8a7e-e325a20d7bcb', 9, 'N.A.L Layout', 'n-a-l-layout-w9', 'South', 20532)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c1e5579-2cc9-4a2d-b882-18f31cefae54', 27, 'Sri Lakshmi Devi Ward', 'sri-lakshmi-devi-ward-w27', 'South', 19844)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '87e7fdba-f2b4-4b68-99f2-c373b8032059', 4, 'Nyayanga Badavane', 'nyayanga-badavane-w4', 'North', 20006)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f440de02-f85a-4eef-a795-0f242b99bcf0', 65, 'Abbigere', 'abbigere-w65', 'North', 21241)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c1e5579-2cc9-4a2d-b882-18f31cefae54', 18, 'Viswamanava Kuvempu Ward', 'viswamanava-kuvempu-ward-w18', 'South', 25500)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 42, 'Priyadarshini Ward', 'priyadarshini-ward-w42', 'East', 16847)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f440de02-f85a-4eef-a795-0f242b99bcf0', 67, 'Shettihalli', 'shettihalli-w67', 'North', 23313)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c1e5579-2cc9-4a2d-b882-18f31cefae54', 21, 'Chikka Adugodi', 'chikka-adugodi-w21', 'South', 21468)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '87e7fdba-f2b4-4b68-99f2-c373b8032059', 7, 'Attur', 'attur-w7', 'North', 26922)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c1e5579-2cc9-4a2d-b882-18f31cefae54', 19, 'New Tavarekere', 'new-tavarekere-w19', 'South', 19251)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 70, 'Iblur', 'iblur-w70', 'South', 27146)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2d2fa9da-a739-4afd-8693-8db51e3aab99', 61, 'HMT Ward', 'hmt-ward-w61', 'North', 29538)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a22834e4-c130-4429-8557-16627aa8596b', 51, 'Manorayanapalya', 'manorayanapalya-w51', 'North', 23684)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 65, 'Garvebavi Palya', 'garvebavi-palya-w65', 'South', 22967)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '98684719-1399-4e24-995d-a6a810f39b4e', 32, 'Kudlu', 'kudlu-w32', 'South', 16661)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c1e5579-2cc9-4a2d-b882-18f31cefae54', 25, 'National Games Village', 'national-games-village-w25', 'South', 19407)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '3410ebdb-6c32-48a2-a567-9a10b793984b', 16, 'Amruthahalli', 'amruthahalli-w16', 'North', 21732)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c1e5579-2cc9-4a2d-b882-18f31cefae54', 22, 'S.G Palya', 's-g-palya-w22', 'South', 21440)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '25ab31b1-80b2-49e8-81e4-22bd802dfd9e', 32, 'Banaswadi', 'banaswadi-w32', 'North', 25077)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '93d13307-f71b-4912-b4bc-6a13f3611c33', 36, 'Someshwara Nagara', 'someshwara-nagara-w36', 'Central', 18863)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '9ef1e023-b17a-4f6f-8a7e-e325a20d7bcb', 12, 'Pattabhirama Nagara', 'pattabhirama-nagara-w12', 'South', 22547)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a22834e4-c130-4429-8557-16627aa8596b', 49, 'Jaya Chamarajendra Nagara', 'jaya-chamarajendra-nagara-w49', 'North', 25953)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 71, 'Agara', 'agara-w71', 'South', 18836)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c1e5579-2cc9-4a2d-b882-18f31cefae54', 23, 'Lakkasandra', 'lakkasandra-w23', 'South', 20932)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '041c179b-1295-46cd-9220-2dc5f68d372d', 27, 'Ambedkarnagar', 'ambedkarnagar-w27', 'Central', 27816)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '3410ebdb-6c32-48a2-a567-9a10b793984b', 13, 'Kodigehalli', 'kodigehalli-w13', 'North', 28244)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2d2fa9da-a739-4afd-8693-8db51e3aab99', 33, 'Lakshmi Devi Nagar', 'lakshmi-devi-nagar-w33', 'West', 24599)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '25ab31b1-80b2-49e8-81e4-22bd802dfd9e', 37, 'Jeevanahalli', 'jeevanahalli-w37', 'North', 28142)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 31, 'Kasavanahalli', 'kasavanahalli-w31', 'South', 21288)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '09e1ec39-9f66-46d8-969c-a99f11b7029d', 39, 'Kaval Byrasandra', 'kaval-byrasandra-w39', 'North', 21965)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c1e5579-2cc9-4a2d-b882-18f31cefae54', 17, 'N.S Palya', 'n-s-palya-w17', 'South', 26701)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 55, 'Puttenahalli', 'puttenahalli-w55', 'South', 21484)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 56, 'Doresanipalya', 'doresanipalya-w56', 'South', 23059)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '09e1ec39-9f66-46d8-969c-a99f11b7029d', 42, 'Aruna Asif Ali Ward', 'aruna-asif-ali-ward-w42', 'North', 29461)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a22834e4-c130-4429-8557-16627aa8596b', 53, 'R.T Nagar', 'r-t-nagar-w53', 'North', 29905)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '09e1ec39-9f66-46d8-969c-a99f11b7029d', 47, 'Pulakeshi Nagar', 'pulakeshi-nagar-w47', 'North', 21148)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '3410ebdb-6c32-48a2-a567-9a10b793984b', 15, 'Byatarayanapura', 'byatarayanapura-w15', 'North', 28870)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c1e5579-2cc9-4a2d-b882-18f31cefae54', 28, 'Kormangala East', 'kormangala-east-w28', 'South', 22885)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '09e1ec39-9f66-46d8-969c-a99f11b7029d', 46, 'Sagayapuram', 'sagayapuram-w46', 'North', 28588)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '25ab31b1-80b2-49e8-81e4-22bd802dfd9e', 24, 'HBR Layout', 'hbr-layout-w24', 'North', 20380)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '09e1ec39-9f66-46d8-969c-a99f11b7029d', 48, 'S.K Garden', 's-k-garden-w48', 'North', 20102)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '3410ebdb-6c32-48a2-a567-9a10b793984b', 14, 'Rajiv Gandhi Nagar', 'rajiv-gandhi-nagar-w14', 'North', 20148)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '25ab31b1-80b2-49e8-81e4-22bd802dfd9e', 28, 'Venkateshpuram', 'venkateshpuram-w28', 'North', 22028)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '25ab31b1-80b2-49e8-81e4-22bd802dfd9e', 36, 'Maruthi Seva Nagara', 'maruthi-seva-nagara-w36', 'North', 24347)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'eca9e102-8d9b-4385-8a19-f09fb5756114', 50, 'JJR Nagara', 'jjr-nagara-w50', 'Central', 27850)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 64, 'Hongasandra', 'hongasandra-w64', 'South', 27790)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 66, 'Singasandra', 'singasandra-w66', 'South', 19089)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 67, 'Bandepalya', 'bandepalya-w67', 'South', 19744)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '09e1ec39-9f66-46d8-969c-a99f11b7029d', 38, 'Shampura', 'shampura-w38', 'North', 21846)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '25ab31b1-80b2-49e8-81e4-22bd802dfd9e', 22, 'Nagavara', 'nagavara-w22', 'North', 20153)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '25ab31b1-80b2-49e8-81e4-22bd802dfd9e', 23, 'Hennur', 'hennur-w23', 'North', 21706)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '93d13307-f71b-4912-b4bc-6a13f3611c33', 34, 'D.V Gundappa Ward', 'd-v-gundappa-ward-w34', 'Central', 20279)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c1e5579-2cc9-4a2d-b882-18f31cefae54', 26, 'Ejipura', 'ejipura-w26', 'South', 22239)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '09e1ec39-9f66-46d8-969c-a99f11b7029d', 44, 'Doddanna Nagar', 'doddanna-nagar-w44', 'North', 29566)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '3410ebdb-6c32-48a2-a567-9a10b793984b', 8, 'Singapura', 'singapura-w8', 'North', 24794)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '04551a39-b049-4bd8-b481-588498172c2e', 10, 'Cox Town', 'cox-town-w10', 'Central', 21026)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 72, 'HSR Layout', 'hsr-layout-w72', 'South', 18787)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '57d45e00-13dc-491b-903f-254661c867de', 65, 'Manjunath Nagara', 'manjunath-nagara-w65', 'West', 20584)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '3410ebdb-6c32-48a2-a567-9a10b793984b', 10, 'Vidyaranyapura', 'vidyaranyapura-w10', 'North', 24887)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 61, 'Kodi Chikkanahalli', 'kodi-chikkanahalli-w61', 'South', 27784)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 60, 'Bilekahalli', 'bilekahalli-w60', 'South', 25208)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '25ab31b1-80b2-49e8-81e4-22bd802dfd9e', 29, 'Lingarajpura', 'lingarajpura-w29', 'North', 26438)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '25ab31b1-80b2-49e8-81e4-22bd802dfd9e', 33, 'HRBR Layout', 'hrbr-layout-w33', 'North', 24637)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '25ab31b1-80b2-49e8-81e4-22bd802dfd9e', 30, 'Kacharakanahalli', 'kacharakanahalli-w30', 'North', 21873)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '041c179b-1295-46cd-9220-2dc5f68d372d', 30, 'Vinayakanagar', 'vinayakanagar-w30', 'Central', 21367)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '57d45e00-13dc-491b-903f-254661c867de', 66, 'Sane Guruvana Halli', 'sane-guruvana-halli-w66', 'West', 20561)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 53, 'Jaraganahalli', 'jaraganahalli-w53', 'South', 22646)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c1e5579-2cc9-4a2d-b882-18f31cefae54', 24, 'A Adugodi', 'a-adugodi-w24', 'South', 21458)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '32c35def-a2ce-4fab-8011-d7797617a42a', 77, 'Maruthi Mandira Ward', 'maruthi-mandira-ward-w77', 'West', 21251)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '32c35def-a2ce-4fab-8011-d7797617a42a', 71, 'Thimmenahalli', 'thimmenahalli-w71', 'West', 23837)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '041c179b-1295-46cd-9220-2dc5f68d372d', 31, 'Shanthinagar', 'shanthinagar-w31', 'Central', 24474)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c1e5579-2cc9-4a2d-b882-18f31cefae54', 29, 'Kormangala West', 'kormangala-west-w29', 'South', 27879)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 54, 'Kengal Hanumanthaiah South', 'kengal-hanumanthaiah-south-w54', 'South', 25484)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c1e5579-2cc9-4a2d-b882-18f31cefae54', 20, 'Madiwala', 'madiwala-w20', 'South', 25538)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'fac027e0-792d-47b5-9d3a-699b0f9c95d1', 48, 'Mathikere', 'mathikere-w48', 'West', 26058)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 62, 'Devarachikkanahalli', 'devarachikkanahalli-w62', 'South', 24847)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2d2fa9da-a739-4afd-8693-8db51e3aab99', 34, 'Peenya', 'peenya-w34', 'West', 26003)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f440de02-f85a-4eef-a795-0f242b99bcf0', 7, 'Rajagopala Nagara', 'rajagopala-nagara-w7', 'West', 24944)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '3410ebdb-6c32-48a2-a567-9a10b793984b', 18, 'Kempapura', 'kempapura-w18', 'North', 28936)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2e03bbc5-c29d-4ea7-8a97-ebdab82e13fa', 93, 'Avalahalli', 'avalahalli-w93', 'West', 24326)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2e03bbc5-c29d-4ea7-8a97-ebdab82e13fa', 87, 'K.P Agrahara', 'k-p-agrahara-w87', 'West', 23555)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '09e1ec39-9f66-46d8-969c-a99f11b7029d', 43, 'Varalakshmi Nagar', 'varalakshmi-nagar-w43', 'North', 26578)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2e03bbc5-c29d-4ea7-8a97-ebdab82e13fa', 88, 'Sangolli Rayanna Ward', 'sangolli-rayanna-ward-w88', 'West', 26299)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '3410ebdb-6c32-48a2-a567-9a10b793984b', 20, 'Sampigehalli', 'sampigehalli-w20', 'North', 28461)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 57, 'Hulimavu', 'hulimavu-w57', 'South', 19598)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '3410ebdb-6c32-48a2-a567-9a10b793984b', 12, 'Thindlu', 'thindlu-w12', 'North', 24289)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 21, 'Uday Nagar', 'uday-nagar-w21', 'East', 20262)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f440de02-f85a-4eef-a795-0f242b99bcf0', 9, 'Srigandhanagar', 'srigandhanagar-w9', 'West', 22361)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a0d11c5c-4c80-4ef9-a399-fafea137c20f', 102, 'Hanumanthanagar', 'hanumanthanagar-w102', 'West', 24583)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '3410ebdb-6c32-48a2-a567-9a10b793984b', 19, 'Thanisandra', 'thanisandra-w19', 'North', 28159)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '3410ebdb-6c32-48a2-a567-9a10b793984b', 17, 'Jakkur', 'jakkur-w17', 'North', 28519)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'fac027e0-792d-47b5-9d3a-699b0f9c95d1', 54, 'Subedarpalya', 'subedarpalya-w54', 'West', 24829)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f440de02-f85a-4eef-a795-0f242b99bcf0', 3, 'Nelagadaranahalli', 'nelagadaranahalli-w3', 'West', 22738)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '3410ebdb-6c32-48a2-a567-9a10b793984b', 9, 'Kuvempunagara', 'kuvempunagara-w9', 'North', 25815)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f92a4030-38b1-4765-baab-a168a3c56049', 47, 'Chandranagara', 'chandranagara-w47', 'South', 22054)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 5, 'Hoysala Nagara East', 'hoysala-nagara-east-w5', 'East', 18244)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '57d45e00-13dc-491b-903f-254661c867de', 58, 'Dayanand Nagara', 'dayanand-nagara-w58', 'West', 21165)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '3410ebdb-6c32-48a2-a567-9a10b793984b', 11, 'Doddabommasandra', 'doddabommasandra-w11', 'North', 25941)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 8, 'Anandapura', 'anandapura-w8', 'East', 18898)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '32c35def-a2ce-4fab-8011-d7797617a42a', 72, 'Kaveripura', 'kaveripura-w72', 'West', 22300)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 58, 'Arakere', 'arakere-w58', 'South', 18995)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 47, 'Bellanduru', 'bellanduru-w47', 'East', 16685)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 20, 'A Narayanapura', 'a-narayanapura-w20', 'East', 21640)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 27, 'Vibhootipura', 'vibhootipura-w27', 'East', 16475)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 33, 'S.M Krishna Ward', 's-m-krishna-ward-w33', 'East', 16262)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2d2fa9da-a739-4afd-8693-8db51e3aab99', 29, 'Chowdeshwari Nagar', 'chowdeshwari-nagar-w29', 'West', 24455)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 49, 'Shivanasamudra Ward', 'shivanasamudra-ward-w49', 'East', 15012)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 18, 'Dooravaninagar', 'dooravaninagar-w18', 'East', 14677)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 68, 'Mangammana Palya', 'mangammana-palya-w68', 'South', 23783)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '9ef1e023-b17a-4f6f-8a7e-e325a20d7bcb', 16, 'Sarakki', 'sarakki-w16', 'South', 23257)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 29, 'Hoodi', 'hoodi-w29', 'East', 20699)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '04551a39-b049-4bd8-b481-588498172c2e', 19, 'Jeevan Bhimanagar', 'jeevan-bhimanagar-w19', 'Central', 27299)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'c35e662c-f45c-48c1-b51c-09b99996cc6c', 38, 'Nandini Layout', 'nandini-layout-w38', 'West', 19639)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 69, 'Hosapalya', 'hosapalya-w69', 'South', 18834)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'fac027e0-792d-47b5-9d3a-699b0f9c95d1', 57, 'Kuvempu Ward', 'kuvempu-ward-w57', 'West', 24283)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 23, 'Sangama Ward', 'sangama-ward-w23', 'East', 15835)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 32, 'Channasandra', 'channasandra-w32', 'East', 14621)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '32c35def-a2ce-4fab-8011-d7797617a42a', 81, 'Nayanda Halli', 'nayanda-halli-w81', 'West', 25982)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '32c35def-a2ce-4fab-8011-d7797617a42a', 73, 'Dr. Vishnuvardhan Ward', 'dr-vishnuvardhan-ward-w73', 'West', 21949)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'b3b4fba5-22d7-4d03-bf47-6908b4a4205a', 107, 'Dharmagiri Ward', 'dharmagiri-ward-w107', 'West', 19154)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2d2fa9da-a739-4afd-8693-8db51e3aab99', 27, 'Srigandada Kaval', 'srigandada-kaval-w27', 'West', 25652)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '60a0221e-9762-4376-b9f6-6b99459671ca', 58, 'Chickpete', 'chickpete-w58', 'Central', 27619)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 31, 'Kadugodi', 'kadugodi-w31', 'East', 18927)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 40, 'Varthur', 'varthur-w40', 'East', 20908)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '32c35def-a2ce-4fab-8011-d7797617a42a', 69, 'Agrahara Dasarahalli', 'agrahara-dasarahalli-w69', 'West', 24742)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 36, 'Bharath Aikya Ward', 'bharath-aikya-ward-w36', 'East', 19498)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 35, 'Garudachar Palya', 'garudachar-palya-w35', 'East', 20983)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '041c179b-1295-46cd-9220-2dc5f68d372d', 26, 'Vannarpet', 'vannarpet-w26', 'Central', 22858)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2e03bbc5-c29d-4ea7-8a97-ebdab82e13fa', 86, 'Vidyaranyanagara', 'vidyaranyanagara-w86', 'West', 28411)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 37, 'Kundalahalli', 'kundalahalli-w37', 'East', 18217)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 34, 'Kaveri Nagara', 'kaveri-nagara-w34', 'East', 20959)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '041c179b-1295-46cd-9220-2dc5f68d372d', 28, 'Neelasandra', 'neelasandra-w28', 'Central', 24853)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 22, 'Mahadevapura', 'mahadevapura-w22', 'East', 17381)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '60a0221e-9762-4376-b9f6-6b99459671ca', 55, 'Bhuvaneshwari Nagar', 'bhuvaneshwari-nagar-w55', 'Central', 19936)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 38, 'Whitefield', 'whitefield-w38', 'East', 20265)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c1e5579-2cc9-4a2d-b882-18f31cefae54', 30, 'Jakkasandra', 'jakkasandra-w30', 'South', 25594)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 50, 'Gunjur', 'gunjur-w50', 'East', 15085)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 13, 'Rajarajeshwari Temple ward', 'rajarajeshwari-temple-ward-w13', 'East', 17539)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 43, 'Dodda Nekkundi', 'dodda-nekkundi-w43', 'East', 16961)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 9, 'Bhattarahalli', 'bhattarahalli-w9', 'East', 14911)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f440de02-f85a-4eef-a795-0f242b99bcf0', 4, 'Parvathi Nagar', 'parvathi-nagar-w4', 'West', 20312)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 26, 'Jagadish Nagar', 'jagadish-nagar-w26', 'East', 18479)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '04551a39-b049-4bd8-b481-588498172c2e', 20, 'Kodihalli', 'kodihalli-w20', 'Central', 24057)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 12, 'Devasandra', 'devasandra-w12', 'East', 14990)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '8c023896-1dbd-49e0-a65d-5c3c4c8e112c', 63, 'Bommanahalli', 'bommanahalli-w63', 'South', 26792)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 3, 'Chellakere', 'chellakere-w3', 'East', 17010)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2d2fa9da-a739-4afd-8693-8db51e3aab99', 26, 'Mallathahalli', 'mallathahalli-w26', 'West', 21575)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 44, 'Ashwath Nagar', 'ashwath-nagar-w44', 'East', 15851)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 30, 'Belathur', 'belathur-w30', 'East', 20869)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'db0dc701-3ac4-43c0-b964-f87f8d033f9f', 48, 'Panathur', 'panathur-w48', 'East', 14766)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'c35e662c-f45c-48c1-b51c-09b99996cc6c', 41, 'Nagapura', 'nagapura-w41', 'West', 26591)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 6, 'Kalkere', 'kalkere-w6', 'East', 17359)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '041c179b-1295-46cd-9220-2dc5f68d372d', 29, 'Austin Town', 'austin-town-w29', 'Central', 19730)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 7, 'K Chennasandra', 'k-chennasandra-w7', 'East', 14572)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '45cfd0c6-6510-4bff-b87d-1a378b587029', 1, 'Ramaswamy Palya', 'ramaswamy-palya-w1', 'Central', 26124)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '0459336b-cf40-4096-85e5-5df334384b91', 24, 'Vignananagara', 'vignananagara-w24', 'East', 14649)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'eca9e102-8d9b-4385-8a19-f09fb5756114', 46, 'Cheluvadi Palya', 'cheluvadi-palya-w46', 'Central', 21019)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '93d13307-f71b-4912-b4bc-6a13f3611c33', 43, 'Devaraj Urs Ward', 'devaraj-urs-ward-w43', 'Central', 19525)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '481035e9-c93a-4424-985a-293e5755ebdf', 15, 'Byadarahalli', 'byadarahalli-w15', 'West', 22784)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '45cfd0c6-6510-4bff-b87d-1a378b587029', 5, 'Shivajinagar', 'shivajinagar-w5', 'Central', 25484)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '041c179b-1295-46cd-9220-2dc5f68d372d', 23, 'Jogpalya', 'jogpalya-w23', 'Central', 25803)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '04551a39-b049-4bd8-b481-588498172c2e', 14, 'Nagavarapalya', 'nagavarapalya-w14', 'Central', 24875)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '57d45e00-13dc-491b-903f-254661c867de', 60, 'Prakash Nagara', 'prakash-nagara-w60', 'West', 19859)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '93d13307-f71b-4912-b4bc-6a13f3611c33', 35, 'Hombegowda Nagara', 'hombegowda-nagara-w35', 'Central', 18866)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '45cfd0c6-6510-4bff-b87d-1a378b587029', 7, 'K Kamaraj Ward', 'k-kamaraj-ward-w7', 'Central', 23193)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '93d13307-f71b-4912-b4bc-6a13f3611c33', 40, 'Ashoka Pillar', 'ashoka-pillar-w40', 'Central', 18989)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '93d13307-f71b-4912-b4bc-6a13f3611c33', 37, 'BHEL Ward', 'bhel-ward-w37', 'Central', 19336)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'eca9e102-8d9b-4385-8a19-f09fb5756114', 45, 'K.R Market', 'k-r-market-w45', 'Central', 22413)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2d2fa9da-a739-4afd-8693-8db51e3aab99', 23, 'Rajarajeshwari Nagara', 'rajarajeshwari-nagara-w23', 'West', 26050)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '45cfd0c6-6510-4bff-b87d-1a378b587029', 6, 'Bharathi Nagar', 'bharathi-nagar-w6', 'Central', 24220)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '041c179b-1295-46cd-9220-2dc5f68d372d', 22, 'Domluru', 'domluru-w22', 'Central', 19982)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '60a0221e-9762-4376-b9f6-6b99459671ca', 60, 'Seshadripuram', 'seshadripuram-w60', 'Central', 19052)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '93d13307-f71b-4912-b4bc-6a13f3611c33', 39, 'Venkat Reddy Nagara', 'venkat-reddy-nagara-w39', 'Central', 18888)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '041c179b-1295-46cd-9220-2dc5f68d372d', 25, 'Ashokanagar', 'ashokanagar-w25', 'Central', 21804)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a0d11c5c-4c80-4ef9-a399-fafea137c20f', 97, 'Srinivasa Nagara', 'srinivasa-nagara-w97', 'West', 25716)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '32c35def-a2ce-4fab-8011-d7797617a42a', 70, 'Dr Rajkumar Ward', 'dr-rajkumar-ward-w70', 'West', 24106)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'fac027e0-792d-47b5-9d3a-699b0f9c95d1', 52, 'Kodandarampura', 'kodandarampura-w52', 'West', 18962)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '481035e9-c93a-4424-985a-293e5755ebdf', 14, 'Herohalli', 'herohalli-w14', 'West', 28413)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '57d45e00-13dc-491b-903f-254661c867de', 59, 'Bandi Reddy Circle Ward', 'bandi-reddy-circle-ward-w59', 'West', 21286)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '481035e9-c93a-4424-985a-293e5755ebdf', 12, 'Andrahalli', 'andrahalli-w12', 'West', 27694)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2e03bbc5-c29d-4ea7-8a97-ebdab82e13fa', 82, 'Attigupe', 'attigupe-w82', 'West', 24614)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '60a0221e-9762-4376-b9f6-6b99459671ca', 61, 'Dattatreya Ward', 'dattatreya-ward-w61', 'Central', 19627)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2e03bbc5-c29d-4ea7-8a97-ebdab82e13fa', 89, 'Bapuji Nagara', 'bapuji-nagara-w89', 'West', 20625)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '32c35def-a2ce-4fab-8011-d7797617a42a', 80, 'Chandra Layout', 'chandra-layout-w80', 'West', 26205)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a0d11c5c-4c80-4ef9-a399-fafea137c20f', 95, 'Swamy Vivekananda Ward', 'swamy-vivekananda-ward-w95', 'West', 28152)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '93d13307-f71b-4912-b4bc-6a13f3611c33', 42, 'Sunkenahalli', 'sunkenahalli-w42', 'Central', 21179)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '93d13307-f71b-4912-b4bc-6a13f3611c33', 32, 'SilverJubilee Park Ward', 'silverjubilee-park-ward-w32', 'Central', 18858)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2e03bbc5-c29d-4ea7-8a97-ebdab82e13fa', 83, 'Hampi Nagar', 'hampi-nagar-w83', 'West', 23420)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '57d45e00-13dc-491b-903f-254661c867de', 63, 'Rajajinagara', 'rajajinagara-w63', 'West', 19632)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '481035e9-c93a-4424-985a-293e5755ebdf', 21, 'Kengeri', 'kengeri-w21', 'West', 21835)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f440de02-f85a-4eef-a795-0f242b99bcf0', 5, 'Rajeshwarinagar', 'rajeshwarinagar-w5', 'West', 25418)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '57d45e00-13dc-491b-903f-254661c867de', 68, 'Kamakshipalya', 'kamakshipalya-w68', 'West', 25024)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'eca9e102-8d9b-4385-8a19-f09fb5756114', 44, 'Chamarajpet', 'chamarajpet-w44', 'Central', 25619)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '04551a39-b049-4bd8-b481-588498172c2e', 15, 'Indiranagar', 'indiranagar-w15', 'Central', 19324)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '45cfd0c6-6510-4bff-b87d-1a378b587029', 3, 'Vasanth Nagar', 'vasanth-nagar-w3', 'Central', 28272)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '481035e9-c93a-4424-985a-293e5755ebdf', 19, 'Shivanapalya', 'shivanapalya-w19', 'West', 21903)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'fac027e0-792d-47b5-9d3a-699b0f9c95d1', 56, 'Gayathri Nagara', 'gayathri-nagara-w56', 'West', 26978)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2e03bbc5-c29d-4ea7-8a97-ebdab82e13fa', 92, 'Muneshwara Block', 'muneshwara-block-w92', 'West', 19922)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '04551a39-b049-4bd8-b481-588498172c2e', 18, 'G.M Palya', 'g-m-palya-w18', 'Central', 20579)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '481035e9-c93a-4424-985a-293e5755ebdf', 18, 'Kengal Hanumanthaiah West', 'kengal-hanumanthaiah-west-w18', 'West', 21223)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'fac027e0-792d-47b5-9d3a-699b0f9c95d1', 55, 'Subramanyanagara', 'subramanyanagara-w55', 'West', 27312)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '04551a39-b049-4bd8-b481-588498172c2e', 16, 'New Thippasandra', 'new-thippasandra-w16', 'Central', 27969)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '481035e9-c93a-4424-985a-293e5755ebdf', 13, 'Nada prabhu Kempegowda Nagara', 'nada-prabhu-kempegowda-nagara-w13', 'West', 27225)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2d2fa9da-a739-4afd-8693-8db51e3aab99', 24, 'Jnana Bharathi Ward', 'jnana-bharathi-ward-w24', 'West', 20533)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '04551a39-b049-4bd8-b481-588498172c2e', 21, 'Konena Agrahara', 'konena-agrahara-w21', 'Central', 26714)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '45cfd0c6-6510-4bff-b87d-1a378b587029', 2, 'Jayamahal', 'jayamahal-w2', 'Central', 25834)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '60a0221e-9762-4376-b9f6-6b99459671ca', 59, 'Nehru Nagar', 'nehru-nagar-w59', 'Central', 25780)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '481035e9-c93a-4424-985a-293e5755ebdf', 16, 'Ullal', 'ullal-w16', 'West', 22549)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '57d45e00-13dc-491b-903f-254661c867de', 64, 'Shivanagara', 'shivanagara-w64', 'West', 20472)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2e03bbc5-c29d-4ea7-8a97-ebdab82e13fa', 90, 'Krishnadevaraya ward', 'krishnadevaraya-ward-w90', 'West', 28148)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '09e1ec39-9f66-46d8-969c-a99f11b7029d', 40, 'Shakthi Nagar', 'shakthi-nagar-w40', 'North', 20035)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f440de02-f85a-4eef-a795-0f242b99bcf0', 10, 'Sunkadakatte', 'sunkadakatte-w10', 'West', 23123)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '25ab31b1-80b2-49e8-81e4-22bd802dfd9e', 27, 'K.G.Halli', 'k-g-halli-w27', 'North', 28238)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'fac027e0-792d-47b5-9d3a-699b0f9c95d1', 51, 'Rajamahal', 'rajamahal-w51', 'West', 24705)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f440de02-f85a-4eef-a795-0f242b99bcf0', 2, 'Chokkasandra', 'chokkasandra-w2', 'West', 27117)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2d2fa9da-a739-4afd-8693-8db51e3aab99', 31, 'Freedom Fighter Ward', 'freedom-fighter-ward-w31', 'West', 18985)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '25ab31b1-80b2-49e8-81e4-22bd802dfd9e', 31, 'Kalyan Nagar', 'kalyan-nagar-w31', 'North', 23746)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'b3b4fba5-22d7-4d03-bf47-6908b4a4205a', 112, 'Hosakerehalli', 'hosakerehalli-w112', 'West', 23619)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '481035e9-c93a-4424-985a-293e5755ebdf', 11, 'Dodda Bidarakallu', 'dodda-bidarakallu-w11', 'West', 25777)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2d2fa9da-a739-4afd-8693-8db51e3aab99', 32, 'Laggere', 'laggere-w32', 'West', 20508)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a0d11c5c-4c80-4ef9-a399-fafea137c20f', 100, 'Srinagar', 'srinagar-w100', 'West', 19229)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '32c35def-a2ce-4fab-8011-d7797617a42a', 74, 'Pattegar Palya', 'pattegar-palya-w74', 'West', 20465)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '25ab31b1-80b2-49e8-81e4-22bd802dfd9e', 26, 'Samadhana Nagar', 'samadhana-nagar-w26', 'North', 20684)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a0d11c5c-4c80-4ef9-a399-fafea137c20f', 96, 'Kathriguppe', 'kathriguppe-w96', 'West', 27696)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '481035e9-c93a-4424-985a-293e5755ebdf', 17, 'Nagadevanahalli', 'nagadevanahalli-w17', 'West', 23269)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a0d11c5c-4c80-4ef9-a399-fafea137c20f', 99, 'T.R Shamanna Nagar', 't-r-shamanna-nagar-w99', 'West', 22292)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a0d11c5c-4c80-4ef9-a399-fafea137c20f', 103, 'N.R Colony', 'n-r-colony-w103', 'West', 27603)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a0d11c5c-4c80-4ef9-a399-fafea137c20f', 104, 'Thyagarajnagar', 'thyagarajnagar-w104', 'West', 21082)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'b3b4fba5-22d7-4d03-bf47-6908b4a4205a', 105, 'Yediyuru', 'yediyuru-w105', 'West', 23023)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a0d11c5c-4c80-4ef9-a399-fafea137c20f', 101, 'Kempambudhi Ward', 'kempambudhi-ward-w101', 'West', 19310)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'b3b4fba5-22d7-4d03-bf47-6908b4a4205a', 111, 'Ittamadu', 'ittamadu-w111', 'West', 19028)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '32c35def-a2ce-4fab-8011-d7797617a42a', 75, 'Marenahalli West', 'marenahalli-west-w75', 'West', 23915)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'b3b4fba5-22d7-4d03-bf47-6908b4a4205a', 109, 'Kamakya Layout', 'kamakya-layout-w109', 'West', 28151)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'b3b4fba5-22d7-4d03-bf47-6908b4a4205a', 110, 'Chikkalasandra', 'chikkalasandra-w110', 'West', 20242)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'b3b4fba5-22d7-4d03-bf47-6908b4a4205a', 106, 'Devagiri Temple Ward', 'devagiri-temple-ward-w106', 'West', 19352)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'b3b4fba5-22d7-4d03-bf47-6908b4a4205a', 108, 'Ganesh Mandira Ward', 'ganesh-mandira-ward-w108', 'West', 24265)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '32c35def-a2ce-4fab-8011-d7797617a42a', 76, 'Moodalapalya', 'moodalapalya-w76', 'West', 19590)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'fac027e0-792d-47b5-9d3a-699b0f9c95d1', 53, 'Malleshwaram', 'malleshwaram-w53', 'West', 21827)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2e03bbc5-c29d-4ea7-8a97-ebdab82e13fa', 91, 'Gali Anjaneya Temple Ward', 'gali-anjaneya-temple-ward-w91', 'West', 22841)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'c35e662c-f45c-48c1-b51c-09b99996cc6c', 40, 'Mahalakshmipuram', 'mahalakshmipuram-w40', 'West', 28125)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2d2fa9da-a739-4afd-8693-8db51e3aab99', 30, 'Kempegowda Layout', 'kempegowda-layout-w30', 'West', 20026)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '57d45e00-13dc-491b-903f-254661c867de', 62, 'Rama Mandira', 'rama-mandira-w62', 'West', 22322)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'c35e662c-f45c-48c1-b51c-09b99996cc6c', 43, 'Kethamaranahalli', 'kethamaranahalli-w43', 'West', 28154)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f440de02-f85a-4eef-a795-0f242b99bcf0', 1, 'Nagasandra', 'nagasandra-w1', 'West', 24974)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'c35e662c-f45c-48c1-b51c-09b99996cc6c', 45, 'Shakthi Ganapathi Nagara', 'shakthi-ganapathi-nagara-w45', 'West', 20838)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '32c35def-a2ce-4fab-8011-d7797617a42a', 78, 'Anubhava Nagara', 'anubhava-nagara-w78', 'West', 23375)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2e03bbc5-c29d-4ea7-8a97-ebdab82e13fa', 94, 'Deepanjali Nagara', 'deepanjali-nagara-w94', 'West', 27561)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2e03bbc5-c29d-4ea7-8a97-ebdab82e13fa', 84, 'Hosahalli', 'hosahalli-w84', 'West', 27966)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f440de02-f85a-4eef-a795-0f242b99bcf0', 6, 'Shivapura', 'shivapura-w6', 'West', 26408)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'c35e662c-f45c-48c1-b51c-09b99996cc6c', 42, 'Raja Mayura Varma Ward', 'raja-mayura-varma-ward-w42', 'West', 27523)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'c35e662c-f45c-48c1-b51c-09b99996cc6c', 44, 'Shankar Mutt', 'shankar-mutt-w44', 'West', 28358)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'c35e662c-f45c-48c1-b51c-09b99996cc6c', 36, 'Nalwadi Krishnaraja Wadiyar Ward', 'nalwadi-krishnaraja-wadiyar-ward-w36', 'West', 28281)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'c35e662c-f45c-48c1-b51c-09b99996cc6c', 37, 'Dr. Puneeth Rajkumar Ward', 'dr-puneeth-rajkumar-ward-w37', 'West', 25126)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '2e03bbc5-c29d-4ea7-8a97-ebdab82e13fa', 85, 'Adi Chunchanagiri Ward', 'adi-chunchanagiri-ward-w85', 'West', 26463)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '57d45e00-13dc-491b-903f-254661c867de', 67, 'Basaveshwara Nagara', 'basaveshwara-nagara-w67', 'West', 20769)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'c35e662c-f45c-48c1-b51c-09b99996cc6c', 39, 'Jai Maruthi Nagar', 'jai-maruthi-nagar-w39', 'West', 27166)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'c35e662c-f45c-48c1-b51c-09b99996cc6c', 46, 'Kamalanagara', 'kamalanagara-w46', 'West', 28196)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'c35e662c-f45c-48c1-b51c-09b99996cc6c', 47, 'Vrishabhavathi Nagar', 'vrishabhavathi-nagar-w47', 'West', 28346)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'a0d11c5c-4c80-4ef9-a399-fafea137c20f', 98, 'Ashoka Nagara', 'ashoka-nagara-w98', 'West', 28420)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'f440de02-f85a-4eef-a795-0f242b99bcf0', 8, 'Hegganahalli', 'hegganahalli-w8', 'West', 28416)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'fac027e0-792d-47b5-9d3a-699b0f9c95d1', 50, 'Sadashiva Nagara', 'sadashiva-nagara-w50', 'West', 19596)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'eca9e102-8d9b-4385-8a19-f09fb5756114', 48, 'Azad Nagar', 'azad-nagar-w48', 'Central', 20270)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '60a0221e-9762-4376-b9f6-6b99459671ca', 56, 'Gopalpura', 'gopalpura-w56', 'Central', 26986)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '60a0221e-9762-4376-b9f6-6b99459671ca', 57, 'Cottonpete', 'cottonpete-w57', 'Central', 27147)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '60a0221e-9762-4376-b9f6-6b99459671ca', 54, 'Binnypete', 'binnypete-w54', 'Central', 25018)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', 'eca9e102-8d9b-4385-8a19-f09fb5756114', 47, 'IPD Salappa Ward', 'ipd-salappa-ward-w47', 'Central', 20622)
  ON CONFLICT (slug) DO NOTHING;
  INSERT INTO wards (city_id, ac_id, ward_number, name, slug, corporation, population)
  VALUES ('97df4146-ef55-4634-855f-cbb226603a4c', '57d45e00-13dc-491b-903f-254661c867de', 61, 'Da.Ra. Bendre Ward', 'da-ra-bendre-ward-w61', 'West', 20756)
  ON CONFLICT (slug) DO NOTHING;
END $$;
